source 'https://github.com/readium/podspecs'
source 'https://cdn.cocoapods.org/'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# set the highest version between react-native framework and what we require
min_ios_version = '15.1'
if Gem::Version.new(min_ios_version_supported) > Gem::Version.new(min_ios_version)
  min_ios_version = min_ios_version_supported
end

platform :ios, min_ios_version
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ReadiumExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  readium_pods

  # Opt-in LCP: liblcp (R2LCPClient) is private and licensed per app by EDRLab, so point
  # READIUM_LCP_PODSPEC at the podspec URL they gave you:
  #   READIUM_LCP_PODSPEC=https://… pod install
  if ENV['READIUM_LCP_PODSPEC']
    pod 'R2LCPClient', :podspec => ENV['READIUM_LCP_PODSPEC']
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    readium_post_install(installer)
  end
end
