source 'https://github.com/readium/podspecs'
source 'https://cdn.cocoapods.org/'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# set the highest version between react-native framework and what we require
min_ios_version = '13.4'
if Gem::Version.new(min_ios_version_supported) > Gem::Version.new(min_ios_version)
  min_ios_version = min_ios_version_supported
end

platform :ios, min_ios_version
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ReadiumExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'ReadiumGCDWebServer', :modular_headers => true
  pod 'ReadiumAdapterGCDWebServer', '~> 3.5.0'
  pod 'ReadiumInternal',  '~> 3.5.0'
  pod 'ReadiumShared',    '~> 3.5.0'
  pod 'ReadiumStreamer',  '~> 3.5.0'
  pod 'ReadiumNavigator', '~> 3.5.0'
  pod 'Minizip', modular_headers: true

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Minizip is a C library whose headers use extern "C" blocks.
    # When react-native-readium enables SWIFT_OBJC_INTEROP_MODE=objcxx,
    # clang tries to compile Minizip as a C++ module, which breaks.
    # Rewrite the modulemap with [extern_c] so clang treats it as C.
    minizip_modulemap = File.join(installer.sandbox.root, 'Headers', 'Public', 'Minizip', 'Minizip.modulemap')
    if File.exist?(minizip_modulemap)
      File.write(minizip_modulemap, <<~MODULEMAP)
        module Minizip [extern_c] [system] {
          header "Minizip-umbrella.h"
          export *
        }
      MODULEMAP
    end
  end
end
