import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Generated by `yarn api` from react-native-readium-lcp's docblocks.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const api = require('./lcp/api/typedoc-sidebar.cjs');

const sidebars: SidebarsConfig = {
  lcp: [
    'index',
    'installation',
    'usage',
    'licenses',
    'errors',
    'custom-client',
    {
      type: 'category',
      label: 'API reference',
      link: { type: 'doc', id: 'api/index' },
      items: api,
    },
  ],
};

export default sidebars;
