import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Generated by `yarn api` from react-native-readium's docblocks.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const api = require('./core/api/typedoc-sidebar.cjs');

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: ['getting-started/installation', 'getting-started/quick-start'],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/opening-publications',
        'guides/navigation',
        'guides/preferences',
        'guides/highlights',
        'guides/search',
        'guides/errors',
        'guides/web',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: ['advanced/content-protection'],
    },
    {
      type: 'category',
      label: 'API reference',
      link: { type: 'doc', id: 'api/index' },
      items: api,
    },
    'supported-formats',
    {
      type: 'category',
      label: 'Migration guides',
      items: ['migration/v5'],
    },
  ],
};

export default sidebars;
